fixing a syntax error when request failed for json
digitalinnovationone/roadmaps pull request #34
Opened 2023-01-28 14:53 UTC by refusado

roadmaps.js - linha 12

O parâmetro da função foi declarado como `erro`, mas a variável usada na foi `error`.
```js
catch (erro) {
        console.log(`Erro ao carregar o arquivo JSON de Roadmap: ${error}\`);
}
```

Dessa forma, ao invés de logar o erro de requisição, um erro de tipagem é obtido, pois a variável usada `error` não foi declarada.

2023-01-30 15:09 UTC, falvojr requested changes
@refusado vlw demais pela colaboração, seu PR tem um valor incrível amigo! Curti demais como ficaram as animações, além das correções na estrutura de pastas (carrers => careers, falha minha 🙈) e tratamento de exceções.
Nesse contexto, gostaria de pedir apenas que sincronize sua branch com a nossa `main`, por favor? É que tínhamos alguns PRs pra subir e acabamos subindo um ajuste que na página da Carreira de CRM que conflitou.
Por fim, apó o seu PR, para evitar que o pessoal que tenha compartilhado nossas páginas com os links antigos tomem 404. Pensei em manter a estrutura de pastas antiga (carrers), com suas respectivas pastas e incluir um index.html de com a meta tag de redirect, o que acha? Assim conseguimos manter os links legados funcionando 😊 Por exemplo, quando alguém acessar a URL `https://digitalinnovationone.github.io/roadmaps/carrers/crm` cairia no seguinte index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="refresh" content="0; url='https://digitalinnovationone.github.io/roadmaps/careers/crm'" />
  </head>
</html>
```

2023-01-31 00:02 UTC, refusado commented
Obrigado, @falvojr !
Realizei as alterações. Mesclei os novos commits à branch e também criei os redirecionamentos como você disse, para evitar que as pessoas que acessarem os links antigos não caiam em um 404.

2023-01-31 02:55 UTC, falvojr approved these changes
Incrível @refusado, muito obrigado pelo apoio amigo! Vou fazer o merge agora 🤩

2023-01-31 02:55 UTC, merged

2023-01-31 03:14 UTC, refusado commented
😍 Obrigado!